---
- hosts: app
  become: yes

  tasks:
    - name: Ensure git is installed
      apt:
        name: git
        state: present

    - name: Clone Django Local Library repository
      git:
        repo: 'https://github.com/mdn/django-locallibrary-tutorial'
        dest: /home/vagrant/local_library
