---
roles:
  - name: docker
    src: https://github.com/AlexPonomarevS/DevOps_lab2.git
    scm: git
    version: main
    path: docker
  - name: nginx
    src: https://github.com/AlexPonomarevS/DevOps_lab2.git
    scm: git
    version: main
    path: nginx

